export type GuideSection = {
  id: string;
  category: string;
  title: string;
  route: string;
  routeLabel: string;
  summary: string;
  controls: readonly string[];
  steps: readonly string[];
  important?: string;
  keywords: readonly string[];
};

const section = (value: GuideSection) => value;

/**
 * Administrator-facing content. Keep this close to the routed Admin surface:
 * routes are intentionally static so a guide link cannot expose an arbitrary
 * member, session, or internal record identifier.
 */
export const GUIDE_SECTIONS: readonly GuideSection[] = [
  section({
    id: 'source-decisions',
    category: 'Annual preparation',
    title: 'Review source conflicts and record amendments',
    route: '/admin/source-review',
    routeLabel: 'Source decisions and changes',
    summary:
      'Keep unresolved policy questions and approved decisions attached to the year and the configuration they affect.',
    controls: [
      '2026 source checks',
      'Record a new change or question',
      'Decision status',
      'Supporting policy',
      'Applies from',
      'Save source decision',
      'Open affected configuration',
      'Decision history',
      'Stored policy language',
    ],
    steps: [
      'Choose the correct year. Open a source check or record a new change. Read the stored policy and inspect the linked configuration before deciding whether the discrepancy is already resolved.',
      'Record the question, affected area, source reference and applicable date. Choose Needs a decision for an unresolved material issue; it blocks a new setup approval while preserving existing approved history.',
      'Choose Resolved only when the authorized policy decision is supported. Record what was decided and its source. Saving preserves all earlier revisions; another administrator cannot silently overwrite your decision.',
      'Apply resulting configuration changes in the linked area, regenerate impact review and practice, then approve through Annual Bid. Recording a source resolution alone does not edit positions, qualifications or policy rules.',
    ],
    important:
      'The 2026 checks identify discrepancies observed in the supplied files. They do not overturn existing approvals or invent new policy. The Daily Shift Staffing Guidelines are not the annual seat-count authority.',
    keywords: [
      'policy',
      'conflict',
      'source',
      'amendment',
      'Labor',
      'Management',
      '2026',
      'decision',
    ],
  }),
  section({
    id: 'change-this-bid',
    category: 'Annual preparation',
    title: 'Change this bid after a Labor/Management decision',
    route: '/admin/annual-plan',
    routeLabel: 'Annual Bid',
    summary:
      'Carry an approved staffing or policy change through dated evidence, configuration, impact review and practice while preserving prior decisions.',
    controls: [
      'Bid year',
      'Organization and seats',
      'Requirements and priorities',
      'Operating policy',
      'Review and impact',
      'Practice and approve',
    ],
    steps: [
      'Confirm the affected bid year and the approved decision, its scope and effective date. Current assignments, future bid opportunities, qualification cutoff and assignment start are separate facts.',
      'For a new, altered or retired authorized position, use Staffing to record the dated structural change. Then use Annual Bid — Organization and seats to include the reviewed opportunity in an editable annual plan. A vacancy is not automatically a bid opening.',
      'For shared qualification, service, points or priority changes, use Requirements and priorities. A narrower position exception must explain which inherited requirement it changes. Preview resolved rules to see the final requirements, alternatives, points, caps, ranking and source profiles together.',
      'For contact, sequencing, A-Day or specialty procedures, use Operating policy. The outcome summary describes what each disposition actually does. Expand its edit controls only when the approved decision changes that behavior.',
      'Save unfinished work to preserve a private editor draft. Restore saved work after returning or signing in again, then recheck the source revision and regenerate the preview. A private draft does not approve or publish a rule.',
      'Use Review and impact to inspect added/removed opportunities, eligibility and ranking changes, preference references and capacity effects. Refresh the review when relevant source evidence changes; the current shared source check remains deliberately conservative.',
      'Run the practice scenarios linked to the current plan and approve only the setup that was reviewed. An approved setup with Real-session history cannot be reopened by editing a form. Use a permitted correction workflow or prepare a future-year draft; never rewrite prior awards or invent a successor authorization.',
    ],
    important:
      'The software executes approved rules but cannot decide which conflicting policy document or amendment Labor/Management adopted. Keep those source questions unresolved until the responsible authority supplies a decision.',
    keywords: [
      'Labor',
      'Management',
      'amendment',
      'change this bid',
      'draft',
      'save',
      'restore',
      'inheritance',
      'exception',
    ],
  }),
  section({
    id: 'targetsolutions',
    category: 'People and qualifications',
    title: 'Import TargetSolutions credentials',
    route: '/admin/targetsolutions',
    routeLabel: 'TargetSolutions import',
    summary:
      'Compare a credential CSV against exact Employee IDs and existing qualification history. Review only changes and exceptions, then apply approved records in resumable groups.',
    controls: [
      'TargetSolutions CSV',
      'Report date',
      'Upload and compare',
      'Resume a saved import',
      'Change categories',
      'Refresh comparison',
      'Review note',
      'Save mapping and compare',
      'Apply reviewed records',
      'Approve this expiration',
      'Approve this revocation',
      'Stop after current group',
      'Previous 100',
      'Next 100',
    ],
    steps: [
      'Export the credential report from TargetSolutions and keep its report header. Select the CSV and choose Upload and compare. Enter a report date only when the file does not contain one; a supplied date cannot contradict the report.',
      'Read the coverage notice. The September 2026 active-only export does not contain issue or expiration dates. Its missing rows never remove, revoke or expire qualifications. Active source records do not automatically earn points.',
      'Choose a category to review new qualifications, missing dates, renewals or exceptions. Employee IDs are exact identities; names are displayed for corroboration only. Unknown IDs must be reconciled in People using authoritative records.',
      'When many unfamiliar names are distinct definitions, expand Review distinct new credential names in one batch. Select the names, confirm they are not existing aliases, and register them with zero points. Failed assessments and reference-only identifiers must still be mapped individually. Registration creates definitions only; inspect and apply the refreshed member changes separately.',
      'For an unfamiliar credential name, enter a review note and choose an existing qualification, a distinct new qualification, or reference-only treatment. Reference-only assessments do not grant a qualification. Failed assessments and DO NOT USE items require explicit classification. Alternatives under a rule are not necessarily the same certificate.',
      'Save the mapping and review the refreshed comparison. Creating a distinct qualification assigns zero informational points; only approved annual rules determine eligibility and scoring.',
      'Enter the review note and choose Apply reviewed records. Ready additions, renewals, missing information and unchanged references are reconciled in groups. The progress report and saved import remain available if interrupted. Temporary Hub authorization failures are retried with increasing waits, for at most five retries. Stop after current group also cancels a pending retry and leaves completed work saved. Denied access and stale reviews are never retried automatically.',
      'Inspect an expiration or revocation individually and use its approval button only after checking the source and existing evidence. Conflicting evidence requires an individual qualification correction and a refreshed comparison.',
      'To correct a saved name mapping, expand Review or correct a saved credential mapping, select the source name and intended destination, and save with a review note. Previous applications remain in history; inspect affected member records for a separate evidence correction.',
      'A source assertion can be rejected with a reason using Keep current record. This preserves the source row, resolves that assertion, and changes no qualification. Rejection is not evidence that the current record has been independently verified.',
      'Resume the saved import to finish remaining items. If a sign-in renewal is needed, use Sign in again and return to this import, enter your review note and apply the remaining records. Re-uploading the same file returns that import rather than duplicating qualifications. Applied records retain the source row and evidence history. Refresh comparison after another administrator updates relevant records.',
    ],
    important:
      'A successful import does not certify that every expiration is current. Blank dates preserve known information. Approved and historical bid evidence is not rewritten by a credential upload. Corrections require source evidence; never change a date just to award points.',
    keywords: [
      'TargetSolutions',
      'Vector',
      'CSV',
      'bulk',
      'mass',
      'sync',
      'expiration',
      'renewal',
      'upload',
      'duplicate',
      'mapping',
    ],
  }),
  section({
    id: 'rules-list',
    category: 'Annual preparation',
    title: 'Requirements and points',
    route: '/admin/rules',
    routeLabel: 'Requirements and points',
    summary:
      'Inspect the selected rule book and open a position rule to review required qualifications, preferred points and tie handling.',
    controls: [
      'Rule book',
      'Position rule',
      'Required criteria',
      'Points preferences',
      'Tie-break order',
    ],
    steps: [
      'Choose the intended year and rule book. Inspect a position and its effective requirements before editing.',
      'Use the annual preparation profiles for shared requirements; use a position-specific exception only when its scope is supported by the policy.',
      'Required qualifications control eligibility. Preferred points and tie-breakers order eligible members. Review the effect in a practice bid before approval.',
    ],
    important:
      'Changing a catalog default is not a change to an approved annual scoring rule. In Advanced completion credit, specify the approved decision, start and end dates, and optional member scope. This permits only the stated scoring item to use recorded completion after expiry; mandatory requirements, prerequisites and revoked records remain excluded. Never enable an exception merely to reproduce a desired score.',
    keywords: ['points', 'rules', 'required', 'preferred', 'tie'],
  }),
  section({
    id: 'qualification-review',
    category: 'People and qualifications',
    title: 'Qualification discrepancies',
    route: '/admin/personnel/reviews',
    routeLabel: 'Qualification review',
    summary:
      'Review separately staged qualification evidence and the source supporting each proposed change.',
    controls: [
      'Source system',
      'Source reference',
      'Review batch',
      'Accept',
      'Reject',
      'Needs review',
      'Apply',
    ],
    steps: [
      'For a TargetSolutions CSV, use Import TargetSolutions credentials. This page retains the existing individual review-batch workflow.',
      'Select the review batch and inspect its source, member reference, qualification and dates.',
      'Resolve identity or qualification mismatches before accepting a row. Record the reviewed decision, then apply accepted evidence using the available action.',
    ],
    important:
      'A review decision and an applied qualification are distinct. Historical bids keep their original evidence.',
    keywords: ['review', 'discrepancy', 'batch', 'accepted'],
  }),
  section({
    id: 'readiness',
    category: 'People and qualifications',
    title: 'Qualification readiness',
    route: '/admin/personnel/readiness',
    routeLabel: 'Qualification readiness',
    summary:
      'Inspect dated qualification evidence and identify expiring or expired records for follow-up.',
    controls: ['Review date', 'Search', 'Classification'],
    steps: [
      'Select the applicable review date and search by person or qualification.',
      'Open the member qualification history to verify the source and record a supported correction or renewal.',
      'Use the selected bid eligibility review to determine the actual effect on bid opportunities.',
    ],
    important:
      'Readiness information does not itself award points or override mandatory qualifications.',
    keywords: ['expired', 'expiring', 'readiness'],
  }),
  section({
    id: 'personnel-operations',
    category: 'Year-round staffing',
    title: 'Temporary assignments and year-round operations',
    route: '/admin/personnel/operations',
    routeLabel: 'Year-round operations',
    summary:
      'Review temporary operational changes while preserving the underlying permanent assignment.',
    controls: [
      'Member',
      'Effective date',
      'Temporary assignment',
      'End assignment',
      'Source and reason',
    ],
    steps: [
      'Select the member and verify the underlying assignment.',
      'Record the authorized temporary change, its effective period and source.',
      'When the temporary assignment ends, record its actual end date and review the resulting staffing view.',
    ],
    important: 'A temporary overlay must not become an unreviewed permanent bid award.',
    keywords: ['temporary', 'light duty', 'operations'],
  }),
  section({
    id: 'new-session',
    category: 'Bid day',
    title: 'Create a bid session',
    route: '/admin/sessions/new',
    routeLabel: 'New bid session',
    summary:
      'Create a practice or real session only from a configuration that meets the applicable readiness checks.',
    controls: ['Bid year', 'Session mode', 'Create session'],
    steps: [
      'Prepare and review the selected annual plan first.',
      'Choose the year and explicitly distinguish practice from real bidding.',
      'Read any readiness blockers and follow the linked preparation workflow. A real session requires the approved configuration and authorized operating policy.',
    ],
    important: 'A practice session is never an official result or a staffing source.',
    keywords: ['new session', 'mock', 'real', 'practice'],
  }),
  section({
    id: 'catalog-import',
    category: 'People and qualifications',
    title: 'Import qualification definitions',
    route: '/admin/credentials/import',
    routeLabel: 'Catalog import',
    summary:
      'Review a spreadsheet of qualification definitions and informational defaults without assigning certificates to people.',
    controls: ['Spreadsheet', 'Import mode', 'Preview', 'Review source', 'Commit'],
    steps: [
      'Use the TargetSolutions importer for member credentials. This catalog import is for qualification definitions.',
      'Select the supported normalized or legacy-wide spreadsheet mode and preview its definitions.',
      'Resolve duplicate labels, identity collisions and retired qualifications before committing the reviewed catalog.',
    ],
    important:
      'This catalog workflow does not synchronize individual member qualifications or change frozen bid points.',
    keywords: ['catalog', 'xlsx', 'definitions'],
  }),
  section({
    id: 'member-import',
    category: 'People and qualifications',
    title: 'Choose a personnel import workflow',
    route: '/admin/members/import',
    routeLabel: 'Personnel import guidance',
    summary: 'Find the controlled replacement for the retired direct roster import.',
    controls: ['TeleStaff import', 'Personnel changes', 'Qualification import'],
    steps: [
      'For assignments and employee reconciliation, follow the TeleStaff workflow.',
      'For an individual employment or rank change, open People and the corresponding dated personnel form.',
      'For member certificates, open Import TargetSolutions credentials.',
    ],
    important:
      'Do not recreate people to resolve an import discrepancy. Preserve existing Employee IDs and account relationships.',
    keywords: ['member import', 'roster', 'identity'],
  }),

  section({
    id: 'tenure',
    category: 'Year-round staffing',
    title: 'Tenure and Protection',
    route: '/admin/personnel/tenure',
    routeLabel: 'Tenure and Protection',
    summary: 'Review dated protection terms for an authorized staffing seat.',
    controls: [
      'Staffing date',
      'Authorized staffing seat',
      'Evidence effective date',
      'Reviewed status',
      'Protected member',
      'Protected from',
      'Protected through (inclusive)',
      'Authoritative source reference',
      'Record reviewed tenure',
      'Evidence history',
    ],
    steps: [
      'Choose the staffing date and authorized seat.',
      'Record the reviewed status. For a protected term, identify the member and exact inclusive dates from the source. Use unknown when a decision is unresolved.',
      'Provide the source and review reason. Saving appends a revision; it does not change an assignment.',
      'In Annual Bid, review the seat participation and canonical holder. Active protection blocks biddable participation and mismatched holder evidence. Expired protection does not close a future annual seat automatically.',
    ],
    important:
      'Absence of a tenure record is not proof of unprotected status. Existing frozen sessions retain their original dated evidence.',
    keywords: ['tenure', 'protection', 'Days', 'term', 'unknown'],
  }),
  section({
    id: 'post-award',
    category: 'Year-round staffing',
    title: 'Post-award Qualifications',
    route: '/admin/personnel/obligations',
    routeLabel: 'Post-award Qualifications',
    summary:
      'Track configured follow-up qualifications against final accepted award events and record reviewed completion evidence.',
    controls: [
      'Official completed bid',
      'Review as of',
      'Review evidence',
      'Review effective date',
      'Reviewed status',
      'Verified completion date',
      'Evidence reference',
      'Record review',
      'Review history',
    ],
    steps: [
      'Configure post-award qualifications separately from initial prerequisites in annual profiles or the individual rule editor. Select final-award timing or an explicit approved bid start date. Cite the authority for the date, period and calendar zone.',
      'After an official bid completes, choose that session and a review date. Read the frozen term, due date and award reference.',
      'Open Review evidence and record completed, pending or unknown status with a dated source and reason. Update Qualification Evidence separately when a certification record requires a change.',
      'Revisions retain their history. A stale revision is rejected and form edits remain available for reconciliation.',
    ],
    important:
      'Missing award evidence leaves the deadline unknown. Award-based terms restart at the final replacement award; approved-start terms retain their frozen date through amendments. Do not substitute session creation or assignment dates for the approved bid start. Calendar-month deadlines clamp to a shorter month’s final day. Past-due review does not remove an assignment or impose discipline.',
    keywords: ['post-award', 'deadline', 'training', 'qualification', 'completion', 'amendment'],
  }),
  section({
    id: 'service-evidence',
    category: 'Year-round staffing',
    title: 'Service Evidence',
    route: '/admin/personnel/service-evidence',
    routeLabel: 'Service Evidence',
    summary:
      'Record dated, source-supported cumulative service totals for annual service requirements without inferring tenure from a current assignment.',
    controls: [
      'Member',
      'Service category',
      'Effective date of this evidence',
      'Verified cumulative completed months',
      'Cumulative service is unknown and requires review',
      'Authoritative source reference',
      'Record reviewed service evidence',
      'Evidence history',
      'Add a service category',
    ],
    steps: [
      'Choose the existing member and service category. Add a category only when an authoritative policy calls for one.',
      'Enter the cumulative completed months supported by the cited source and the effective date. Select unknown when the evidence cannot establish a total.',
      'Provide the source reference and reason, then save. Later corrections create a new revision and preserve earlier dated evidence.',
      'Add the service category and minimum months in the annual profile or position rule editor. Review annual participant evidence before freezing.',
    ],
    important:
      'Totals are reviewed source facts, not automatically calculated months. Unknown evidence does not satisfy a service requirement. Saved frozen sessions keep their original service evidence.',
    keywords: [
      'rescue division',
      '36 months',
      'service evidence',
      'cumulative service',
      'unknown',
      'history',
    ],
  }),
  section({
    id: 'annual-plan',
    category: 'Annual preparation',
    title: 'Annual Bid',
    route: '/admin/annual-plan',
    routeLabel: 'Annual Bid',
    summary:
      'Start or resume the designated annual draft and review organization, dated participant evidence and scoped rules.',
    controls: [
      'Preparation year',
      'Annual preparation stages',
      'Start annual draft',
      'Adopt reviewed draft into annual preparation',
      'Add reviewed seat to annual plan',
      'Save reviewed annual seat',
      'Confirm reviewed removal',
      'Add profile',
      'Preview resolved rules',
      'Save reviewed rules',
      'Export full review and impact',
      'Save source review checkpoint',
      'Create Mock from reviewed configuration',
      'Approve reviewed bid setup',
      'Upcoming Board',
    ],
    steps: [
      'Choose the year and resume a saved draft, start blank, or select a verified official prior completion. Enter reviewed personnel and qualification dates, duration and turn timer.',
      'An existing unpublished designated draft can enter guided preparation through Adopt reviewed draft. Review its dates and confirm the proposal. Shared templates, published configurations and years with a Real session require their existing protected configuration path.',
      'Maintain organization and authorized seats, then select each annual seat with explicit participation and staffing characteristics. Include a source reference and reason.',
      'Use Review seat to reconcile an inherited seat while keeping its identity. Removal requires a source, reason and explicit confirmation. After a conflict, refresh the plan while retaining edits, inspect the current seats, then choose Use reviewed revision and keep edits before resubmitting.',
      'Review dated personnel and qualifications in stage 3; correct evidence through Personnel Changes or Qualification Evidence.',
      'In stage 4, author department, rank, station/shift, explicitly selected family, or individual-position profiles. Add all required prerequisites and define the total, Special Operations and Marine Operations points channels. Add ranking priorities in order.',
      'Preview resolved rules and inspect their source profiles before saving. Requirements accumulate; the most specific points and priority definitions apply. Equal-specificity conflicts require correction.',
      'In stage 6, choose the selected official completion or last saved source review as the comparison baseline. Rule effects hold current evidence constant; evidence effects hold prior rules constant. Candidate priorities preserve ties and do not predict choices or awards. Filter results, move through all pages, or export the complete review.',
      'Save source review checkpoint to preserve the current prepared evidence for later comparisons. A checkpoint does not publish rules or approve a freeze. Refresh and explicitly adopt displayed revisions if a newer source invalidates your retained review.',
      'In stage 7, create a Mock from the reviewed configuration and run it in the Rehearsal Console. If its response is lost, Retry same Mock creation request. Select a completed Mock and review its findings before freezing. The server verifies its completion receipt and exact configuration, then publishes the rule book and annual policy atomically.',
    ],
    important:
      'Changing stages does not approve a review or start a session. Stale drafts retain edits and require review before saving. A blank points channel explicitly awards zero in that channel.',
    keywords: [
      'annual plan',
      'prepare next bid',
      'scoped profiles',
      'points',
      'requirements',
      'priorities',
      'resume',
      'review',
    ],
  }),
  section({
    id: 'organization',
    category: 'Year-round staffing',
    title: 'Organization',
    route: '/admin/organization',
    routeLabel: 'Organization',
    summary:
      'Maintain stable stations, organizational groups, and apparatus even before seats exist.',
    controls: [
      'Viewing date',
      'Add organization',
      'Parent',
      'Effective on',
      'Lifecycle',
      'Authoritative source reference',
      'History',
      'Link a reviewed seat to organization',
    ],
    steps: [
      'Create a station or organizational group with a reviewed effective date and source reference. Creating an organization creates no seats.',
      'Create apparatus under an existing reviewed station or group. Use Edit for a dated rename, move, or retirement.',
      'Review dependency details before retirement. Close or move dependent apparatus and explicitly review seat links first.',
      'Use the seat-link form to associate an existing authorized seat with an organization on the viewing date. Occupancy and source-system labels remain separate.',
    ],
    important:
      'A later revision must be reviewed before editing an earlier dated view. Historical names and links remain available in history; no inferred organization-to-seat mapping is created.',
    keywords: [
      'station 7',
      'empty station',
      'organization',
      'apparatus',
      'rename station',
      'effective date',
      'dependency',
      'seat link',
    ],
  }),
  section({
    id: 'bid-board',
    category: 'Year-round staffing',
    title: 'Bid Board',
    route: '/admin/bid-board',
    routeLabel: 'Bid Board',
    summary:
      'Compare verified previous awards, effective-dated current staffing, and upcoming annual seats in independent views.',
    controls: [
      'Previous Bid',
      'Completed official bid',
      'Current Staffing',
      'Upcoming Bid',
      'Shift',
      'Annual plan',
      'Staffing as of',
      'Search this view',
      'Source and revision details',
    ],
    steps: [
      'Select the view and shift. Upcoming also requires a designated annual year.',
      'Previous defaults to the latest verified completion. Choose a specific completed official bid to keep reviewing that cycle. Returning to the page or refocusing it checks for newer completions without changing a specifically selected cycle.',
      'Use the staffing date to inspect the canonical assignments effective on that day. Temporary context preserves the underlying assignment.',
      'Review the source details and lifecycle before interpreting a seat. Previous uses frozen historical names when available; Upcoming contains no occupants.',
    ],
    important:
      'No verified official completion means Previous is unavailable. A staffing vacancy is not permission to bid a seat. Background refresh retains the last successful data for the same selection when a request fails.',
    keywords: [
      'previous bid',
      'current staffing',
      'upcoming bid',
      'board',
      'frozen awards',
      'unmapped',
      'temporary assignment',
    ],
  }),
  section({
    id: 'getting-started',
    category: 'Start here',
    title: 'Getting started',
    route: '/admin',
    routeLabel: 'Dashboard',
    summary:
      'Use Bid through your authorized MBFD Hub sign-in. The Admin Console is for year-round staffing administration and controlled Bid operations.',
    controls: ['Admin navigation', 'Navigation button on mobile', 'Sidebar links'],
    steps: [
      'Enter Bid from MBFD Hub with your authorized account.',
      'Use the left navigation on desktop; select Navigation on a phone or tablet.',
      'Use Mock Bids for rehearsal. Live Bid is a separate, operator-only workspace.',
    ],
    important:
      'Hub authentication and the Bid Access PIN serve different purposes. Never treat a PIN as a Hub sign-in method.',
    keywords: ['login', 'hub', 'sidebar', 'mobile navigation', 'year round', 'mock vs real bid'],
  }),
  section({
    id: 'dashboard',
    category: 'Start here',
    title: 'Dashboard',
    route: '/admin',
    routeLabel: 'Dashboard',
    summary:
      'The dashboard is the control-center landing page. Read its status cards and use its shortcuts to move into the area that needs attention.',
    controls: ['Status cards', 'Operational shortcuts', 'Admin navigation'],
    steps: [
      'Review the status shown before making a change.',
      'Use a shortcut to open the related workspace.',
      'Follow blocked or unavailable notices instead of working around them.',
    ],
    important:
      'A dashboard status is an operational signal, not authorization to start a live Bid or change controlled records.',
    keywords: ['status', 'cards', 'shortcuts', 'attention'],
  }),
  section({
    id: 'current-rosters',
    category: 'Year-round staffing',
    title: 'Current Rosters',
    route: '/admin/current-rosters',
    routeLabel: 'Current Rosters',
    summary:
      'View the reviewed operational staffing projection by A, B, C, D, or all shifts, including vacancies and people not assigned to a reviewed seat.',
    controls: [
      'Search',
      'Shift selector',
      'As-of date',
      'Vacancies and unassigned filters',
      'Reset filters',
      'CSV download',
      'Print roster',
    ],
    steps: [
      'Choose an effective date and shift scope.',
      'Use search and the vacancy or unassigned filters to narrow the projection.',
      'Review the roster summary, then download CSV or open the print view when an export is needed.',
    ],
    important:
      'This page reports the reviewed projection. Resolve a staffing question in its source workflow rather than editing a roster display.',
    keywords: [
      'roster',
      'a shift',
      'b shift',
      'c shift',
      'd shift',
      'vacancy',
      'unassigned',
      'csv',
      'print',
      'pdf',
      'as of date',
    ],
  }),
  section({
    id: 'staffing-structure',
    category: 'Year-round staffing',
    title: 'Staffing Structure',
    route: '/admin/staffing-structure',
    routeLabel: 'Staffing Structure',
    summary:
      'Maintain authorized staffing seats and their occupancy history. An authorized seat is the approved slot; an occupant is the member assigned to that slot.',
    controls: [
      'Add authorized staffing seat form',
      'Effective-date filters',
      'Capacity and occupancy view',
      'Retire seat action',
    ],
    steps: [
      'Set the effective date before reviewing capacity.',
      'Add a seat only when the authorized structure supports it.',
      'Use the seat history and occupancy information to confirm the change.',
      'Retire a seat only with the reviewed effective date and reason.',
    ],
    important:
      'Do not create a seat just to accommodate an unmatched source row. A seat and a member assignment are separate controlled records.',
    keywords: [
      'authorized seat',
      'occupant',
      'vacant',
      'add seat',
      'retire seat',
      'reassignment',
      'effective date',
      'capacity',
    ],
  }),
  section({
    id: 'telestaff',
    category: 'Year-round staffing',
    title: 'TeleStaff',
    route: '/admin/telestaff',
    routeLabel: 'TeleStaff',
    summary:
      'TeleStaff is a controlled reconciliation workflow: upload, preview, stage, reconcile, review, and then apply only reviewed, safe results.',
    controls: [
      'Upload',
      'Preview',
      'Stage',
      'Reconcile',
      'Review',
      'Apply',
      'Designate selected-year staffing baseline',
      'Sanitized reconciliation export',
    ],
    steps: [
      'Confirm whether the source is official or synthetic and verify the snapshot date.',
      'Upload and inspect the preview before staging it.',
      'Reconcile changes, new positions, unknown employees, incomplete topology, and source mappings.',
      'Review safe exceptions and export the sanitized reconciliation package when needed.',
      'Apply only after reviewed exceptions are resolved or formally retained.',
      'After a committed official import passes completeness checks, use the two-step baseline confirmation. It will atomically supersede the prior acceptance receipt while preserving that receipt in audit history.',
    ],
    important:
      'Never invent a seat or identity for an unknown employee or incomplete topology. Baseline confirmation writes an acceptance receipt to production D1, but it does not start a Bid session and does not write back to TeleStaff.',
    keywords: [
      'telestaff',
      'upload',
      'preview',
      'stage',
      'reconcile',
      'apply',
      'unknown employee',
      'incomplete topology',
      'source mapping',
      'sanitized export',
      'baseline',
      'supersede',
    ],
  }),
  section({
    id: 'members',
    category: 'People and qualifications',
    title: 'Members and Member Roster',
    route: '/admin/members',
    routeLabel: 'Members',
    summary:
      'Find members, open their profile and assignment context, and use the Master Roster for searchable roster review and order controls where available.',
    controls: [
      'Member list',
      'Profile links',
      'Member Roster',
      'Search by name or employee ID',
      'Roster filters',
      'Move up and down controls',
    ],
    steps: [
      'Open Members to find a record.',
      'Open the member profile to review assignment context and history.',
      'Use Member Roster to search or review roster-level information.',
      'Use Personnel Changes for controlled lifecycle changes instead of treating a profile as an edit surface.',
    ],
    important:
      'Member records and their operational assignment history are not interchangeable with a staffing seat.',
    keywords: [
      'member',
      'member roster',
      'profile',
      'search member',
      'employee id',
      'history',
      'assignment context',
    ],
  }),
  section({
    id: 'credentials',
    category: 'People and qualifications',
    title: 'Credentials & Specialty Points',
    route: '/admin/credentials',
    routeLabel: 'Credentials & Specialty Points',
    summary:
      'Use the credential catalog and member credential records to understand qualification holders and specialty-point values.',
    controls: [
      'Credential catalog',
      'Add credential',
      'Edit display name and default points',
      'Retirement date and dependency preview',
      'Search credentials',
      'Holder count',
      'Member credential records',
      'Credential import workflow',
    ],
    steps: [
      'Review the credential catalog and holder count.',
      'Choose Edit to change a display name, informational points, or retirement date. Supply a reason for the audited change.',
      'Review active and draft policies, referenced members, qualification history events, and frozen snapshots before retirement. Historical evidence remains unchanged. If another administrator changes the record, preserve your notes, cancel the stale edit, and reopen the current record.',
      'Open the related member record to inspect qualification context.',
      'For a catalog spreadsheet, open Import Qualification Catalog and choose the layout. A normalized XLSX has name and fy_points_default columns. For a legacy matrix, explicitly enter the number of leading employee metadata columns; existing default points are preserved.',
      'Select Preview proposed changes. Review every proposed create, update and unchanged entry, and resolve every reported error. Previewing does not change the catalog or grant qualifications to members.',
      'Enter the authoritative source reference and review reason, check the review confirmation, and apply the reviewed import. A changed catalog requires regenerating and reviewing the proposal. After a lost response, retry the unchanged submission to retrieve its original receipt.',
      'Confirm whether you are viewing year-round values or frozen annual-Bid values.',
    ],
    important:
      'A frozen annual-Bid value is evidence for that Bid; it is not a shortcut for changing the year-round credential record.',
    keywords: ['credential', 'specialty points', 'holder count', 'member credential', 'points'],
  }),
  section({
    id: 'personnel',
    category: 'People and qualifications',
    title: 'Personnel Changes',
    route: '/admin/personnel',
    routeLabel: 'Personnel Changes',
    summary:
      'Record effective-dated personnel lifecycle and assignment changes while preserving an immutable history of what changed and why.',
    controls: [
      'Change type',
      'Effective date',
      'Member and assignment fields',
      'Reason',
      'Preview/history',
      'Temporary overlays',
    ],
    steps: [
      'Choose the reviewed change type: new hire, promotion, demotion, transfer, reassignment, retirement, separation, or correction.',
      'Set the effective date and complete the relevant member and assignment fields.',
      'Review the preview and history before committing.',
      'Record the reason and retain any policy-pending or configuration-pending status.',
      'After a successful save, personnel and dependent staffing and annual-plan views refresh automatically. Previous Bid retains its completed historical evidence.',
    ],
    important:
      'Use a correction to correct a reviewed record; do not overwrite historical facts. Temporary overlays are distinct from permanent staffing changes.',
    keywords: [
      'new hire',
      'promotion',
      'demotion',
      'transfer',
      'reassignment',
      'retire member',
      'retirement',
      'separation',
      'correction',
      'effective date',
      'history',
    ],
  }),
  section({
    id: 'qualification-evidence',
    category: 'People and qualifications',
    title: 'Qualification Evidence & Review',
    route: '/admin/personnel/qualifications',
    routeLabel: 'Qualification Evidence',
    summary:
      'Record whether a qualification is gained, expires, or is revoked, and use the review areas to understand readiness and Bid eligibility impact.',
    controls: [
      'Qualification lifecycle',
      'Evidence fields',
      'Qualification Review',
      'Readiness view',
    ],
    steps: [
      'Open Qualification Evidence for the relevant member and qualification.',
      'Record the lifecycle event and supporting evidence.',
      'Use Qualification Review to identify items needing review.',
      'Check readiness before relying on a qualification for eligibility.',
    ],
    important:
      'Specialty-qualified status and supporting evidence must remain traceable; do not mark an unverified qualification as ready.',
    keywords: [
      'qualification',
      'gain',
      'expire',
      'revoke',
      'specialty qualified',
      'evidence',
      'readiness',
      'eligibility',
    ],
  }),
  section({
    id: 'bid-setup',
    category: 'Annual preparation',
    title: 'Bid Setup',
    route: '/admin/bid-setup',
    routeLabel: 'Bid Setup',
    summary:
      'Bid Setup organizes the annual preparation sequence and shows whether the selected year has usable configuration.',
    controls: [
      'Bid year',
      'Configuration status',
      'Rule Books',
      'Positions',
      'Rules',
      'Eligibility Preview',
      'Bid Access PIN',
    ],
    steps: [
      'Select the Bid year.',
      'Review configuration status and resolve blocking or unconfigured conditions.',
      'Prepare controlled rules, positions, policy, and eligibility before creating a session.',
      'Use the related setup links rather than bypassing a blocked configuration.',
    ],
    important: 'A year with missing or blocking configuration is not ready for live operations.',
    keywords: [
      'bid setup',
      'annual preparation',
      'configuration',
      'bid year',
      'blocking',
      'unconfigured',
    ],
  }),
  section({
    id: 'rule-books',
    category: 'Annual preparation',
    title: 'Rule Books',
    route: '/admin/rule-books',
    routeLabel: 'Rule Books',
    summary:
      'Rule Books hold controlled Bid rules as drafts and revisions. Publishing is a deliberate, protected action with a recorded reason.',
    controls: [
      'Create draft',
      'Rule Book form',
      'Revision reason',
      'Publish action',
      'Publish confirmation',
    ],
    steps: [
      'Create or open the appropriate draft.',
      'Record scope and the reviewed operational reason.',
      'Review coverage and revision details.',
      'Publish only when the authorized revision is ready.',
    ],
    important:
      'Published rules are controlled evidence. Do not publish a draft merely to make a configuration appear complete.',
    keywords: ['rule book', 'draft', 'revision', 'publish', 'published rules'],
  }),
  section({
    id: 'positions-rules',
    category: 'Annual preparation',
    title: 'Positions & Rules',
    route: '/admin/positions',
    routeLabel: 'Positions',
    summary:
      'Review configured positions by shift and open a position rule to manage participation, rank or category criteria, eligibility, and tie-break order.',
    controls: [
      'Shift position list',
      'Edit configured rule',
      'Rank checkboxes',
      'Eligibility criteria',
      'Tie-break order controls',
      'Save rule',
    ],
    steps: [
      'Choose the relevant shift and position.',
      'Open its configured rule.',
      'Review participation, category or rank, eligibility, and tie-break settings.',
      'Save only the reviewed rule change and re-check the result.',
    ],
    important: 'Position rules define eligibility; do not change them to fit an individual result.',
    keywords: [
      'position',
      'rules',
      'participation',
      'rank',
      'category',
      'eligibility',
      'tie break',
    ],
  }),
  section({
    id: 'eligibility-preview',
    category: 'Annual preparation',
    title: 'Eligibility Preview',
    route: '/admin/eligibility',
    routeLabel: 'Eligibility Preview',
    summary:
      'Eligibility Preview shows how current configuration evaluates eligibility before an award is made.',
    controls: ['Eligibility form', 'Position and member inputs', 'Preview result'],
    steps: [
      'Select the applicable configuration and subject.',
      'Run the preview.',
      'Review why the result is eligible, ineligible, or unavailable.',
      'Correct the underlying controlled record if authoritative review requires it.',
    ],
    important: 'A preview is not an award and does not change a live session.',
    keywords: ['eligibility preview', 'eligible', 'ineligible', 'preview not award'],
  }),
  section({
    id: 'bid-pin',
    category: 'Annual preparation',
    title: 'Bid Access PIN',
    route: '/admin/settings/bid-pin',
    routeLabel: 'Bid Access PIN',
    summary:
      'The Bid Access PIN is an additional operational access control used in the Bid application; it is separate from MBFD Hub authentication.',
    controls: ['PIN input', 'Change PIN button'],
    steps: [
      'Confirm you are authorized to change the PIN.',
      'Enter the new approved PIN in the protected form.',
      'Complete the change and communicate it only through the approved channel.',
    ],
    important: 'Do not share a PIN in this guide, in exports, or in regular administrative notes.',
    keywords: ['pin', 'change pin', 'bid access', 'hub authentication'],
  }),
  section({
    id: 'annual-policy',
    category: 'Annual preparation',
    title: 'Annual Policy',
    route: '/admin/annual-policy',
    routeLabel: 'Annual Policy',
    summary:
      'Annual Policy builds an executable, versioned policy for Bid stages, order, specialty handling, dispositions, contact requirements, A-Day limits, and revision evidence.',
    controls: [
      'Policy version',
      'Bid stages and order',
      'Live action authority',
      'Disposition rules',
      'Contact policy',
      'Specialty policy',
      'A-Day limits',
      'Preview and revision history',
    ],
    steps: [
      'Start with the approved year and policy version.',
      'Configure and order stages, specialty policy, dispositions, contacts, and A-Day limits.',
      'Review blocking or unconfigured status and correct it through the approved policy process.',
      'Use preview and revision history before publishing or freezing evidence.',
    ],
    important:
      'Keep policy-pending and unconfigured states visible. A frozen policy preserves what governed that annual Bid.',
    keywords: [
      'annual policy',
      'change bid order',
      'stages',
      'specialty policy',
      'disposition',
      'contact policy',
      'a-day',
      'frozen policy',
      'policy pending',
    ],
  }),
  section({
    id: 'bid-advisory',
    category: 'Rehearse and operate',
    title: 'BID Advisory',
    route: '/admin/bid',
    routeLabel: 'Live Bid & Advisory',
    summary:
      'BID Advisory immediately describes authoritative results already calculated by deterministic BID application rules. There is no AI or model generation delay.',
    controls: ['Read-only advisory cards', 'Evidence-source labels', 'Authoritative sequence'],
    steps: [
      'Open Live Bid & Advisory for the active or selected session.',
      'Read the advisory sequence and evidence labels with the live board.',
      'Use the controlled Bid workspace for any authorized operational action.',
    ],
    important:
      'Decision Details explain why the current result is displayed. They do not make decisions, change eligibility, award positions, calculate a second outcome, or change staffing, policy, assignments, or session state.',
    keywords: ['advisory', 'explain', 'candidate order', 'position options', 'authoritative state'],
  }),
  section({
    id: 'mock-bids',
    category: 'Rehearse and operate',
    title: 'Mock Bids',
    route: '/admin/rehearsal',
    routeLabel: 'Mock Bids',
    summary:
      'Mock Bids are isolated rehearsals for validating sequence, selections, amendments, specialty handling, order changes, findings, and operator readiness.',
    controls: [
      'Active Mock Sessions',
      'Findings',
      'Auto Bid',
      'Freeze rehearsal',
      'Reset mock',
      'Close stale mock',
      'Verify audit',
    ],
    steps: [
      'Create or select a mock session.',
      'Use rehearsal controls to run the scenario and record findings.',
      'Freeze, reset, or close the mock using the explicit control when appropriate.',
      'Verify the mock audit before treating the rehearsal as complete.',
    ],
    important:
      'Mock commands remain isolated from canonical staffing and portal writeback. Do not start a real Bid just to test a workflow.',
    keywords: [
      'mock',
      'rehearsal',
      'test bid',
      'freeze mock',
      'reset mock',
      'close mock',
      'auto bid',
      'findings',
    ],
  }),
  section({
    id: 'live-bid',
    category: 'Rehearse and operate',
    title: 'Live Bid',
    route: '/admin/bid',
    routeLabel: 'Live Bid',
    summary:
      'Live Bid is the operator console for an authorized administrator running an actual Bid session. It shows the active bidder, on-deck members, timer, phase, and protected controls.',
    controls: [
      'Current bidder',
      'On deck',
      'Pick for member',
      'Skip',
      'Override',
      'Freeze',
      'Session controls',
    ],
    steps: [
      'Confirm the session, phase, active bidder, and on-deck order.',
      'Only the authorized Admin or operator records a live selection.',
      'Use protected skip, override, or freeze controls only with the required operational reason.',
      'Use session controls for pause or resume where the session state permits.',
    ],
    important:
      'Ordinary members do not make live selections here. Skip, override, and freeze are consequential actions and can require step-up authorization.',
    keywords: [
      'live bid',
      'current bidder',
      'on deck',
      'select position',
      'skip',
      'override',
      'freeze',
      'pause',
      'resume',
      'operator only',
    ],
  }),
  section({
    id: 'specialty-adjudication',
    category: 'Rehearse and operate',
    title: 'Specialty Adjudication',
    route: '/admin/specialty-adjudication',
    routeLabel: 'Specialty Adjudication',
    summary:
      'Specialty Adjudication records a controlled specialty review with the original bidder, eligible higher-priority candidates, points or rank, contacts, outcomes, and exact resumption state.',
    controls: [
      'Specialty review state',
      'Candidate list',
      'Contact attempts',
      'Accept',
      'Decline',
      'Pass',
      'Unreachable',
      'Evidence and reason fields',
    ],
    steps: [
      'Start the specialty review from the live controls when authorized.',
      'Review the original bidder, requested position, candidate order, and policy status.',
      'Record each contact attempt and disposition.',
      'Complete the adjudication and confirm the suspended bidder resumes at the recorded queue state.',
    ],
    important:
      'This area includes synthetic rehearsal support. Keep synthetic and real activity distinct, and do not substitute a synthetic result for live evidence.',
    keywords: [
      'specialty',
      'adjudication',
      'higher priority',
      'points',
      'ranking',
      'contact attempts',
      'accept',
      'decline',
      'unreachable',
      'suspended bidder',
      'resume',
    ],
  }),
  section({
    id: 'live-presentation',
    category: 'Rehearse and operate',
    title: 'Live Presentation',
    route: '/admin/bid',
    routeLabel: 'Live Bid',
    summary:
      'Department presentation controls decide what the presentation shows: OFF, LIVE, HOLD DISPLAY, or RESUME DISPLAY.',
    controls: [
      'OFF',
      'LIVE',
      'HOLD DISPLAY',
      'RESUME DISPLAY',
      'Operator reason',
      'Evidence reference',
    ],
    steps: [
      'Enter the required operator reason and any policy-required evidence reference.',
      'Choose the intended display mode.',
      'Check the command response before continuing operations.',
    ],
    important:
      'HOLD DISPLAY is not the same as pausing Bid execution. Display controls do not pause the live Bid.',
    keywords: [
      'presentation',
      'hold presentation',
      'hold display',
      'resume presentation',
      'live display',
      'off',
    ],
  }),
  section({
    id: 'results-audit',
    category: 'Records and handoff',
    title: 'Results & Audit',
    route: '/admin/audit',
    routeLabel: 'Audit Log',
    summary:
      'Results & Audit helps you review recorded events and the immutable evidence associated with controlled actions.',
    controls: [
      'Event filter',
      'Date filters',
      'Search',
      'Audit results',
      'Exports',
      'Bid Award Transition',
    ],
    steps: [
      'Choose the event and date filters.',
      'Search for the relevant record.',
      'Review the recorded action and supporting context.',
      'Use the related Exports or Award Transition workspace when appropriate.',
    ],
    important:
      'Immutable evidence means the system preserves the recorded operational history; it does not mean every item is automatically approved for downstream action.',
    keywords: ['results', 'audit', 'audit log', 'immutable evidence', 'event filter'],
  }),
  section({
    id: 'exports',
    category: 'Records and handoff',
    title: 'Exports',
    route: '/admin/exports',
    routeLabel: 'Exports',
    summary:
      'Exports provides controlled roster and Bid export generation, direct CSV downloads, available packages, and portal-sync status.',
    controls: [
      'Select a session',
      'Generate',
      'Direct CSV downloads',
      'Available exports',
      'Retry action',
      'Portal sync status',
    ],
    steps: [
      'Select the intended session when the export requires one.',
      'Choose the correct export type or direct CSV download.',
      'Wait for the generated package to appear and verify its scope before distributing it.',
      'Review portal-sync status rather than assuming a write occurred.',
    ],
    important:
      'An export is evidence or a file delivery mechanism; it does not itself authorize a staffing or portal change.',
    keywords: ['export', 'csv', 'roster export', 'bid export', 'download', 'portal sync'],
  }),
  section({
    id: 'award-transition',
    category: 'Records and handoff',
    title: 'Bid Award Transition',
    route: '/admin/award-transition',
    routeLabel: 'Bid Award Transition',
    summary:
      'Bid Award Transition is a fail-closed review workspace for a completed Bid becoming future staffing on a selected effective date.',
    controls: [
      'Completed Bid selection',
      'Assignment comparison',
      'Effective date',
      'Reason',
      'Review acknowledgement',
      'Apply reviewed transition',
    ],
    steps: [
      'Select a completed Bid from its session controls.',
      'Review current-to-new assignments and the effective date.',
      'Record the reviewed reason and acknowledgement.',
      'Apply only when the transition is authorized and the workspace allows it.',
    ],
    important:
      'Portal writeback is currently disabled. Do not represent a reviewed transition as portal writeback or assume external systems were changed.',
    keywords: [
      'award transition',
      'post bid',
      'future staffing',
      'writeback',
      'portal writeback',
      'completed bid',
    ],
  }),
  section({
    id: 'system-integrations',
    category: 'Records and handoff',
    title: 'System & Integrations',
    route: '/admin/system',
    routeLabel: 'System/Integrations',
    summary:
      'System & Integrations presents user-facing health and integration status for Hub federation, TeleStaff, and writeback safety.',
    controls: ['Health and status indicators', 'Integration status'],
    steps: [
      'Review the displayed status before relying on an integration.',
      'Use the related operational workspace for any permitted action.',
      'Treat unavailable or fail-closed status as a stop for the dependent action.',
    ],
    important:
      'A healthy status indicator does not grant permission to deploy, change external systems, or enable writeback.',
    keywords: [
      'system',
      'integration',
      'health',
      'hub federation',
      'telestaff',
      'writeback safety',
    ],
  }),
  section({
    id: 'common-workflows',
    category: 'Help and safety',
    title: 'Common workflows',
    route: '/admin/current-rosters',
    routeLabel: 'Current Rosters',
    summary:
      'Use these short paths to begin common tasks without turning the guide into a single long procedure.',
    controls: ['Open this page links', 'Section navigation', 'Guide search'],
    steps: [
      'Update staffing: Current Rosters → Staffing Structure or Personnel Changes.',
      'Process TeleStaff: TeleStaff → upload → preview → stage → reconcile → review → apply.',
      'Add or promote a member: Personnel Changes → effective date → preview/history → record.',
      'Prepare a Bid: Bid Setup → Rule Books/Positions/Policy → Eligibility Preview → controlled session.',
      'Run a rehearsal: Mock Bids → findings → verify audit.',
      'Export safely: Results & Audit → Exports → verify package scope.',
    ],
    important:
      'For specialty requests, prior-selection amendments, presentation controls, and live operations, use their dedicated guide sections before acting.',
    keywords: [
      'workflow',
      'add employee',
      'promote member',
      'retire member',
      'run mock bid',
      'finish bid safely',
      'export roster',
    ],
  }),
  section({
    id: 'troubleshooting-safety',
    category: 'Help and safety',
    title: 'Troubleshooting & safety',
    route: '/admin/system',
    routeLabel: 'System/Integrations',
    summary:
      'Use the displayed condition and its source workflow to resolve missing records, unavailable actions, policy holds, stale advisory state, and Mock-versus-live confusion safely.',
    controls: ['Status indicators', 'Blocked notices', 'Step-up prompts', 'Guide search'],
    steps: [
      'Member or position missing: verify the effective date and source workflow; do not invent an assignment or seat.',
      'TeleStaff row unknown or incomplete: retain the exception and seek authoritative mapping.',
      'Button unavailable or step-up required: confirm authorization and the required state before retrying.',
      'Policy blocking or unconfigured: complete the approved policy/configuration work.',
      'Advisory sequence behind the board: reload Live Bid and verify the authoritative sequence before acting.',
    ],
    important:
      'Never start a real Bid merely to test it, and never treat Mock Bid behavior as proof of live authorization or a canonical staffing change.',
    keywords: [
      'troubleshooting',
      'member missing',
      'position missing',
      'button unavailable',
      'step up',
      'blocking',
      'unconfigured',
      'stale advisory',
      'mock vs live',
    ],
  }),
  section({
    id: 'glossary',
    category: 'Help and safety',
    title: 'Glossary',
    route: '/admin/guide',
    routeLabel: 'Administrator Guide',
    summary:
      'Plain-language definitions for the terms used across year-round staffing, annual Bid preparation, and live operations.',
    controls: ['Search', 'Category navigation', 'Expandable sections'],
    steps: [
      'Canonical roster: the reviewed operational roster record.',
      'Authorized position: an approved staffing seat; vacancy: an unoccupied authorized seat.',
      'Assignment: a member’s placement; effective date: when a change takes effect.',
      'Reconciliation: review of source information against controlled records; source mapping: an approved connection to source data.',
      'Frozen policy: the preserved policy evidence for an annual Bid; Bid stage: an ordered phase of the process.',
      'Specialty interruption: a controlled pause for specialty review; step-up authentication: an additional confirmation for protected actions.',
      'Mock/rehearsal: isolated practice; live presentation: what the department display shows; audit evidence: the preserved record of an action.',
    ],
    keywords: [
      'glossary',
      'canonical roster',
      'authorized position',
      'vacancy',
      'assignment',
      'effective date',
      'reconciliation',
      'frozen policy',
      'bid stage',
      'step up authentication',
    ],
  }),
];

/** Every Admin navigation destination must be represented in guide content. */
export const ADMIN_GUIDE_COVERAGE: Readonly<Record<string, readonly string[]>> = {
  '/admin': ['getting-started', 'dashboard'],
  '/admin/docs': ['glossary'],
  '/admin/targetsolutions': ['targetsolutions'],
  '/admin/bid-board': ['bid-board'],
  '/admin/current-rosters': ['current-rosters', 'common-workflows'],
  '/admin/staffing-structure': ['staffing-structure', 'organization'],
  '/admin/telestaff': ['telestaff'],
  '/admin/members': ['members', 'credentials'],
  '/admin/personnel': ['personnel', 'qualification-evidence'],
  '/admin/annual-plan': ['annual-plan', 'annual-policy'],
  '/admin/bid-setup': [
    'bid-setup',
    'rule-books',
    'positions-rules',
    'eligibility-preview',
    'bid-pin',
    'annual-policy',
  ],
  '/admin/rehearsal': ['mock-bids'],
  '/admin/bid': ['bid-advisory', 'live-bid', 'specialty-adjudication', 'live-presentation'],
  '/admin/audit': ['results-audit', 'exports', 'award-transition'],
  '/admin/system': ['system-integrations', 'troubleshooting-safety'],
};

export const GUIDE_CATEGORIES = [...new Set(GUIDE_SECTIONS.map((item) => item.category))];

export function filterGuideSections(query: string): readonly GuideSection[] {
  const terms = query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return GUIDE_SECTIONS;

  return GUIDE_SECTIONS.filter((item) => {
    const searchable = [
      item.title,
      item.category,
      item.summary,
      ...item.controls,
      ...item.steps,
      ...item.keywords,
    ]
      .join(' ')
      .toLocaleLowerCase();
    return terms.every((term) => searchable.includes(term));
  });
}
